version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 121181250737.dkr.ecr.us-east-1.amazonaws.com
      - echo Building java application
      - mvn clean package
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 121181250737.dkr.ecr.us-east-1.amazonaws.com/questions-ms:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 121181250737.dkr.ecr.us-east-1.amazonaws.com/questions-ms:latest
      - echo Writing image definitions file...
      - printf '[{"name":"question-ms","imageUri":"%s"}]' 121181250737.dkr.ecr.us-east-1.amazonaws.com/questions-ms:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes